In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
session_cattagory = {}
def get_test_train_data_from_csv(hum_file = "../parsed_data/human.csv",bot_file = "../parsed_data/bots.csv"):

    df_bots = pd.read_csv(bot_file)
    df_bots["bot"] = 1
    df_bots
    for ses in df_bots.iloc[:,0].values:
        session_cattagory[ses] = 1

    df_hum = pd.read_csv(hum_file)
    df_hum["bot"] = 0
    df_hum
    for ses in df_hum.iloc[:,0].values:
        session_cattagory[ses] = 0
    df_merged = pd.concat([df_bots, df_hum], ignore_index=True, sort=False)
    df_merged

    X = df_merged.iloc[:, 1:-1].values
    Y = df_merged.iloc[:, -1].values
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test,

In [15]:
X_train, X_test, y_train, y_test = get_test_train_data_from_csv("../parsed_data/human.csv","../parsed_data/bots.csv")

In [16]:
len(session_cat)

813

In [27]:
session_cattagory["p7g6ccuqqfum0pbfk5q82nhnam"]

0

In [1]:
import numpy as np

arr1 = np.array([[1, 2],[2, 3]])
arr2 = np.array([[4, 5],[4, 6]])
arr3 = np.array([[4, 5],[4, 6]])

stacked_h = np.stack((arr1, arr2,arr3), axis=0)[..., np.newaxis]
print("Horizontal stack:\n", stacked_h)

Horizontal stack:
 [[[[1]
   [2]]

  [[2]
   [3]]]


 [[[4]
   [5]]

  [[4]
   [6]]]


 [[[4]
   [5]]

  [[4]
   [6]]]]


In [19]:
arr1.shape

(2, 2)

In [20]:
stacked_h.shape

(3, 2, 2, 1)

In [22]:
arr1 = arr1[...,np.newaxis]

In [23]:
arr1.shape

(2, 2, 1)

In [12]:
a = [np.random.randint(low=0,high=11) for i in range(30)]

In [13]:
a

[1,
 4,
 7,
 5,
 6,
 0,
 6,
 8,
 7,
 1,
 10,
 6,
 10,
 6,
 8,
 9,
 3,
 0,
 8,
 9,
 0,
 6,
 2,
 7,
 8,
 1,
 4,
 6,
 1,
 0]